name: Check Markdown links

on:
  push:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Check links in markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: './markdown-link-check-config.json'
  lint-changelog:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Markdown linter
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: '**.md'
